chainID: 8453
nodeURL: https://mainnet.base.org
nativeCurrencySymbol: ETH
minGasPrice: 0.1
# EIP-1559 gas parameters (in GWEI)
# If not set, will fetch from network
maxFeePerGas: 0.1
maxPriorityFeePerGas: 0.01
